name: Backmerge after PR merged to master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:

  backmerge_master_into_edge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
        with:
          ref: edge
      - name: Merge master into edge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull -r origin master
      - name: Push to branch
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push $remote_repo staging

  backmerge_master_into_staging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
        with:
          ref: edge
      - name: Merge origin master into staging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull -r origin master
      - name: Push to branch
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push $remote_repo staging
