name: Run tests and increment version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  increment_version:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: staging

      - name: Make release
        env:
          BRANCH_NAME: ${{ toJson(github).head_ref }}
        run: |
          git config --local user.email "release-action@github.com"
          git config --local user.name "GitHub Release Action"
          npm version $(echo $BRANCH_NAME | grep -o [0-9\.] | xargs |  sed 's/ //g')
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
