name: PR Made To Master

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  make_release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
            ref: staging
      - run: .github/workflows/make_release.sh
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
