name: Merge to master

on:
  push:
    branches:
      - master

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout edge
        uses: actions/checkout@v1
        with:
          ref: edge
        run: git merge origin/master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: edge


