name: Merge to master

on:
  push:
    branches:
      - master

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: edge
    - run: git config --global user.email "aholachek@stashinvest.com"
    - run: git config --global user.name "Alex"
    - run: git merge origin/master
    - run: git push origin edge



