name: Merge to master

on:
  push:
    branches:
      - master

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        git fetch
        git merge staging origin/master
        git merge edge origin/master
        git push origin staging
        git push origin edge


