name: Merge to master

on:
  push:
    branches:
      - master

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/checkout@v1
      with:
        ref: edge
    - run: git merge origin/master
    - run: git push origin edge



